version: '3.4'

services:
    sql-server-db:
        container_name: sql-server-db
        image: microsoft/mssql-server-windows-developer
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Password@1"
            ACCEPT_EULA: "Y"
        volumes:
            - C:\TempSQLServer:c:\TempSQLServer

